### PR TITLE
Fix a dutycycle-related deadlock in ScheduleTx

### LINKED ISSUE #1288: Dutycycle-related deadlock in ScheduleTx
I think there is a deadlock in the function `ScheduleTx` which manifests itself at the end of a dutycycle-enforced quiet period while the MAC is retransmitting an uplink. If `RegionNextChannel` returns a zero `DutyCycleWaitTime`, the function forgoes creating `TxDelayedTimer` and returns immediately:
https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/LoRaMac.c#L2911-L2933

Thus, `ScheduleTx` is never re-executed and the MAC is stuck in a busy state forever. `McpsConfirm` for the uplink will never get invoked.

The fix is to move the statement `return LORAMAC_STATUS_OK` inside the block where the delayed timer is started. I have submitted a PR with the fix: #1287

### PR DESCRIPTION
**Pull request by janakj**
If we get a "dutycycle restricted" status with a zero dutycycle wait time from `RegionNextChannel`, attempt to transmit the uplink message right away. There is no need to check whether delayed TX is allowed or start the delayed TX timer in this case.

Only abort with `LORAMAC_STATUS_DUTYCYCLE_RESTRICTED` if we actually get a non-zero dutycycle wait time with delayed transmissions prohibited.

The previous implementation deadlocks during uplink retransmissions in dutycycled bands. Upon leaving a dutycycle-enforced quiet period, `RegionNextChannel` may return `LORAMAC_STATUS_DUTYCYCLE_RESTRICTED` with a zero dutycycle wait time. `ScheduleTx` was programmed to forgo the creation of the delayed TX timer, thus never getting re-executed to complete the transmission. The MAC would be stuck in a busy state.

Closes #1288

### CODE REVIEW

**Comment by janakj** [comment]
Fixes #1288

**Comment by MarekNovakACRIOS** [comment]
If I inderstand well the situation - the frame was dropped even if no timer is started - your modification is a good catch. But - status is not OK in the part of the code and gets overwritten by VerifyTxFrame(). This could be maybe somehow addressed...

**Comment by janakj** [comment]
I am not sure I follow. What's the problem with VerifyTxFrame?

The way I read the code, the condition that checks if DutyCycleWaitTime is
zero is actually a performance optimization that skips the creation of a
timer that would have fired immediately. In this case, the ScheduleTx
should proceed as if no duty-cycling was necessary.

**Comment by janakj** [comment]
Perhaps you mean the case when RegionNextChannel returns LORAMAC_STATUS_DUTYCYCLE_RESTRICTED while allowDelayedTx is false? That indeed deserves a second look as the function should also proceed normally in this case. The value of allowDelayedTx is probably irrelevant when DutyCycleWaitTime == 0.

So perhaps this PR needs one more commit.

**Comment by MarekNovakACRIOS** [comment]
@janakj , sorry for being brief, I was checking the PR on the phone.

I overall agree with your PR, but what I don't like, is that the value of status  checked at line 2914 to not be OK (!=LORAMAC_STATUS_OK) is silently ignored in your codepath and the value is overwritten by the call of VerifyTxFrame( ); at line 2939.

**Comment by janakj** [comment]
> I overall agree with your PR, but what I don't like, is that the value of status checked at line 2914 to not be OK (!=LORAMAC_STATUS_OK) is silently ignored in your codepath and the value is overwritten by the call of VerifyTxFrame( ); at line 2939.

What's wrong with that? The inner block is a single if-else condition where the else block returns the status. Thus, it's only ignored if the status value is LORAMAC_STATUS_DUTYCYCLE_RESTRICTED and no timer is necessary.

**Comment by MarekNovakACRIOS** [comment]
> > I overall agree with your PR, but what I don't like, is that the value of status checked at line 2914 to not be OK (!=LORAMAC_STATUS_OK) is silently ignored in your codepath and the value is overwritten by the call of VerifyTxFrame( ); at line 2939.
> 
> What's wrong with that? The inner block is a single if-else condition where the else block returns the status. Thus, it's only ignored if the status value is LORAMAC_STATUS_DUTYCYCLE_RESTRICTED and no timer is necessary.

I double checked and you are right. I agree with the PR as is.
It will save the day for many people hitting the duty cycle!

**Comment by mluis1** [comment]
Thanks for the proposition.

From my point of view this PR looks good. However I would like to have @djaeckle approval.

**Comment by abxy** [comment]
Nice job! One potential issue I can see is that when `RegionNextChannel` returns `LORAMAC_STATUS_DUTYCYCLE_RESTRICTED` no "next channel" has been selected (at least this is the case for EU868). I think this means that the last channel will re-used. Whether this is a problem or not I'll leave to someone more knowledgeable to determine.

**Comment by janakj** [comment]
> Nice job! One potential issue I can see is that when `RegionNextChannel` returns `LORAMAC_STATUS_DUTYCYCLE_RESTRICTED` no "next channel" has been selected (at least this is the case for EU868). I think this means that the last channel will re-used. Whether this is a problem or not I'll leave to someone more knowledgeable to determine.

Good point! You might be right about channel reuse in this case. However, this will only happen in one specific corner case: when the returned dutycycle wait time is zero. One could argue that the function should not return `LORAMAC_STATUS_DUTYCYCLE_RESTRICTED` in this case, but that's for more capable people than myself to look into.

In any case, channel reuse is probably better than a deadlock.

**Comment by djaeckle** [comment]
Hi all,

thanks for the analysis. I have done a review and i'm fine with the code adaptations. I followed also #1255 and asked there also more questions. In general, i think its a very nice finding.

**Comment by janakj** [comment]
@djaeckle @mluis1 Any chance to get this merged? Or is anything still holding the merge up?

File: src/mac/LoRaMac.c [hunk 1]
```diff
@@ -2901,18 +2901,22 @@ static LoRaMacStatus_t ScheduleTx( bool allowDelayedTx )
...
-            // Allow delayed transmissions. We have to allow it in case
-            // the MAC must retransmit a frame with the frame repetitions
             if( MacCtx.DutyCycleWaitTime != 0 )
-            {// Send later - prepare timer
-                MacCtx.MacState |= LORAMAC_TX_DELAYED;
-                TimerSetValue( &MacCtx.TxDelayedTimer, MacCtx.DutyCycleWaitTime );
-                TimerStart( &MacCtx.TxDelayedTimer );
+            {
+                if( allowDelayedTx == true )
+                {
```
Comment (MedadRufus) [inline src/mac/LoRaMac.c:2909]: All three if statements can be combined into single statement with &&
